import { LegalPage, type LegalSection } from "@/components/legal-page";
import { createPageMetadata } from "@/lib/site-config";

export const metadata = createPageMetadata({
	title: "Terms of Use",
	description:
		"Terms that apply when using the ResourceDocs static-analysis and documentation-generation service.",
	path: "/terms",
});

const sections: LegalSection[] = [
	{
		id: "acceptance",
		title: "Acceptance",
		content: (
			<>
				<p>
					These Terms of Use govern access to ResourceDocs, a
					documentation-generation service operated by Hasts Studio. By using
					the service, you agree to these terms. If you do not agree, do not use
					ResourceDocs.
				</p>
				<p>
					You must be legally able to enter these terms and comply with the laws
					that apply to you.
				</p>
			</>
		),
	},
	{
		id: "service",
		title: "The service",
		content: (
			<>
				<p>
					ResourceDocs statically analyzes accessible FiveM and RedM files and
					can generate documentation for configuration, dependencies, exports,
					events, commands, and installation. Features, limits, providers, and
					availability may change.
				</p>
				<p>
					The service does not execute uploaded scripts and does not attempt to
					decrypt or bypass Cfx.re Asset Escrow.
				</p>
			</>
		),
	},
	{
		id: "uploads",
		title: "Your uploads",
		content: (
			<>
				<p>
					You keep ownership of files and content you upload. You grant Hasts
					Studio a limited permission to process that content only as needed to
					analyze it, generate requested documentation, secure the service, and
					provide the result.
				</p>
				<p>
					You represent that you have the rights and permissions needed to
					upload the content and to send extracted facts to configured AI
					providers. Do not upload credentials, personal data, malware, unlawful
					content, or another person&apos;s confidential code without
					authorization.
				</p>
			</>
		),
	},
	{
		id: "acceptable-use",
		title: "Acceptable use",
		content: (
			<>
				<p>
					You may not misuse ResourceDocs, interfere with its operation, evade
					limits, probe other users&apos; data, upload harmful archives, attempt
					unauthorized access, use the service to bypass escrow protections, or
					violate intellectual property, privacy, export-control, or other
					applicable laws.
				</p>
				<p>
					We may restrict or block requests that threaten the service, its
					providers, or other users.
				</p>
			</>
		),
	},
	{
		id: "generated-output",
		title: "Generated output",
		content: (
			<>
				<p>
					Documentation is generated from static analysis and may include
					AI-written descriptions. ResourceDocs is designed to keep technical
					identifiers tied to verified facts, but static analysis and AI output
					can still be incomplete or incorrect.
				</p>
				<p>
					You are responsible for reviewing generated documentation, testing
					examples, confirming installation steps, and deciding whether the
					output is suitable before publishing or relying on it.
				</p>
			</>
		),
	},
	{
		id: "intellectual-property",
		title: "Intellectual property",
		content: (
			<>
				<p>
					ResourceDocs, its interface, brand, and original software are owned by
					Hasts Studio or its licensors. These terms do not transfer ownership
					of the service or third-party technologies.
				</p>
				<p>
					FiveM, RedM, Cfx.re, Rockstar Games, Google, Gemini, Vercel, and other
					names belong to their respective owners. ResourceDocs is not
					affiliated with Cfx.re or Rockstar Games.
				</p>
			</>
		),
	},
	{
		id: "availability",
		title: "Availability and limits",
		content: (
			<>
				<p>
					The service may be changed, suspended, rate-limited, or discontinued.
					Free access and model availability are not guaranteed. We may impose
					file, request, token, or daily usage limits to protect reliability and
					cost.
				</p>
			</>
		),
	},
	{
		id: "disclaimers",
		title: "Disclaimers",
		content: (
			<>
				<p>
					ResourceDocs is provided on an “as is” and “as available” basis to the
					extent permitted by law. We do not promise uninterrupted operation,
					complete source discovery, compatibility with every resource, or
					error-free generated documentation.
				</p>
				<p>
					Nothing generated by ResourceDocs is legal, security, financial, or
					professional advice.
				</p>
			</>
		),
	},
	{
		id: "liability",
		title: "Limitation of liability",
		content: (
			<>
				<p>
					To the maximum extent permitted by law, Hasts Studio will not be
					liable for indirect, incidental, special, consequential, exemplary, or
					punitive damages, or for lost profits, data, goodwill, or business
					opportunities arising from use of the service.
				</p>
				<p>
					Some jurisdictions do not allow certain limitations, so parts of this
					section may not apply to you.
				</p>
			</>
		),
	},
	{
		id: "changes",
		title: "Changes and contact",
		content: (
			<>
				<p>
					We may update these terms and will post the updated version with a new
					effective date. Continued use after an update means you accept the
					revised terms where permitted by law.
				</p>
				<p>
					Questions about these terms can be directed to Hasts Studio through
					its <a href="https://hastherish.com">official website</a>.
				</p>
			</>
		),
	},
];

export default function TermsPage() {
	return (
		<LegalPage
			title="Terms of Use"
			description="The rules for using ResourceDocs, uploading source files, and reviewing generated documentation."
			sections={sections}
		/>
	);
}
